"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['drove.py']
DATA_FILES = [
    'assets',
]
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'assets/AppIcon.icns',
    'packages': ['pygame', 'pygame-essentials'],
    'excludes': [
        'test',
        'tests',
        'tkinter.test',
        'idlelib',
        'unittest.test',
        'doctest',
        'distutils.tests',
        'setuptools.tests',
        'numpy',
        'scipy',
        'PIL',
        'Pillow',
        'pygame.tests',
        'pygame.examples',
    ],
    'plist': {
        'CFBundleIdentifier': 'com.ethandadev.drove',
        'CFBundleVersion': '0.1.0',
        'CFBundleName': 'Drove',
        'CFBundleDisplayName': 'Drove',
        'CFBundleShortVersionString': '0.1.0',
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)